version: '3.5'
services:
  kommu_db:
    image: postgres:11-alpine
    container_name: kommu_db
    environment:
      POSTGRES_DB: kommu
      POSTGRES_PASSWORD: kommu_password
      POSTGRES_USER: kommu
    networks: [kommu]
    ports:
      - 5432:5432
  kommu:
    image: kommu_development:1.0
    environment:
      #DB CONFIGURATION
      DB_HOST: kommu_db
      DB_NAME: kommu
      DB_PASSWORD: kommu_password
      DB_USER: kommu
      NODE_ENV: development_docker
      PORT: 8000
      DEBUG_PORT: 9228
      KOMMU_DB_PORT: 5432
    container_name: kommu
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    ports:
      - 8000:8000
      - 9228:9228
    depends_on:
      - kommu_db
    networks: [kommu]

networks:
  kommu:
    name: kommu
    driver: bridge
